> # ** Solução - Exercícios Extras (Aula 5) - visualização com Altair** 

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ry4n-felinto/impytech_2026/blob/main/aula_05/aula05_EXTRA_exercicios.ipynb)

- **Professor:** Ryan Kevin
  - al.ryan.felinto@impatech.edu.br

- **Monitores:**
  - Bianca Zavadisk
    - al.bianca.abreu@impatech.edu.br
  - Bruno Paula
    - al.bruno.paula@impatech.edu.br
  - Pedro Alberti
    - al.pedro.alberti@impatech.edu.br
  - Cristiane Sampaio
    - al.cristiane.sampaio@impatech.edu.br

- **Desenvolvedores:**
   - Bruno Paula
      - al.bruno.paula@impatech.edu.br

 ## **Introdução a manipulação e visualização de dados**

**Nota:** Este notebook tem o objetivo de utilizar a biblioteca `altair` ao invés da `matplotlib.pyplot`. 

Para mais informações quanto à sintaxe do Altair, consulte a [documentação oficial](https://altair--viz-github-io.translate.goog/user_guide/data.html?_x_tr_sl=en&_x_tr_tl=pt&_x_tr_hl=pt&_x_tr_pto=tc).

---

> ## **Problema 0 - Importação de bibliotecas** 🟢
Na célula abaixo importe as bibliotecas que serão utilizadas: `pandas`, `altair` e `numpy`.

In [2]:
# TODO: importe as bibliotecas
import pandas as pd
import altair as alt
import numpy as np

In [10]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

> ## **Problema 1 - Expressão Genética** 🟢

Suponha que você e seu grupo de pesquisa estão fazendo um levantamento para descobrir uma relação entre a expressividade genética e o tumor.
Neste levantamento, vocês escolheram dois genes específicos: `TP53` e `BRCA1`.

### 📝 **Problema 1.1**

**🎯 Objetivo:** Usando a biblioteca pandas leia o arquivo `dados_expressao_genes.csv`, visualize de forma simples a tabela.

In [4]:
# TODO: leia o arquivo `dados_rastreamento_albert.csv`
df = pd.read_csv('dados_expressao_genes.csv')

# TODO: visualize de forma resumida a estrutura das tabelas
df.head()

  Genes Amostra_ID     Grupo  Expressao
0  TP53     Ctrl_1  Controle       12.5
1  TP53     Ctrl_2  Controle       13.4
2  TP53     Ctrl_3  Controle       12.3
3  TP53     Ctrl_4  Controle       11.7
4  TP53     Ctrl_5  Controle       11.9

### 📝 **Problema 1.2**

**🎯 Objetivo:** Usando uma filtragem simples, faça um histograma comparando a quantidade de amostras de cada grupo de controle para o genes `TP53`.

In [11]:
#TODO: Filtre o dados 
geneTP53_df = df[df['Genes'] == 'TP53']

#TODO: Conte os dados de cada grupo 
geneTP53_counts = geneTP53_df.groupby('Grupo').size()

#TODO: Crie o gráfico
alt.Chart(geneTP53_counts.reset_index(name='counts')).mark_bar().encode(
    x='Grupo:N',
    y='counts:Q'
).properties(
    title='Contagem de TP53 por Grupo'
)

alt.Chart(...)

### 📝 **Problema 1.3**

**🎯 Objetivo:** Usando uma filtragem simples, faça um histograma comparando a quantidade de amostras de cada grupo de controle para o genes `BRCA1`.

In [12]:
#TODO: Filtre o dados
geneBRCA1_df = df[df['Genes'] == 'BRCA1']

#TODO: Conte os dados de cada grupo
geneBRCA1_counts = geneBRCA1_df.groupby('Grupo').size()

#TODO: Crie o gráfico

#Dica: Siga os mesmos passos da problema anterior

alt.Chart(geneBRCA1_counts.reset_index(name='counts')).mark_bar().encode(
    x='Grupo:N',
    y='counts:Q'
).properties(
    title='Contagem de BRCA1 por Grupo'
)

alt.Chart(...)

### 📝 **Problema 1.4**
**🎯 Objetivo:** Visualize de forma organizada com o objetivo de verificar a relação do grupo de controle com a expressividade dos dois genes.

**OBS:** Este exercício admite muitas formas de criar, seja criativo.

In [18]:
#TODO: Crie uma visualização

alt.Chart(df).mark_point().encode(
    y='Genes:N',
    x='Expressao:Q',
    color='Grupo:N',
    tooltip=['Amostra_ID', 'Genes', 'Expressao', 'Grupo']
).properties(
    title='Expressão de Genes por Grupo',
    height=150,
)

alt.Chart(...)

> ## **Problema 2 - Deslocamento do verme *C. elegans.*** 🟡

Suponha que você está em grupo de pesquisa que está estudando comportamento de vermes da espécie *Caenorhabditis elegans* (verme muito utilizado em pesquisas).
Neste experimento você e seu grupo coletaram as posições relativas de um indíviduo desta espécie, que carinhosamente iremos chamar de `Albert`.  
Dessa forma, neste experimento iremos extrair os dados coletados, manipular esses dados e gerar visualizações.

### 📝 **Problema 2.1**

**🎯 Objetivo:** Usando a biblioteca pandas leia o arquivo `dados_rastreamento_albert.csv`, visualize de forma simples a tabela e verifique a integrabilidade dos dados.

In [ ]:
# TODO: leia o arquivo `dados_rastreamento_albert.csv`
df = pd.read_csv('dados_rastreamento_albert.csv')

# TODO: visualize de forma resumida a estrutura das tabelas
df.info()

# TODO: Visualize informações da tabela
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tempo   100 non-null    int64
 1   x       98 non-null     float64
 2   y       99 non-null     float64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

             tempo          x          y
count  100.000000  98.000000  99.000000
mean    50.500000  20.132627   0.056944
std     29.011492  11.642698   1.792393
min      1.000000   0.474500  -2.584400
25%     25.750000  10.042875  -1.738100
50%     50.500000  20.092050   0.214800
75%     75.250000  29.777775   1.775050
max    100.000000  39.964800   2.715400

   tempo       x       y
0      1  0.4745  0.5973
1      2  0.7793  1.3695
2      3  1.2972  1.9240
3      4  1.8285  2.2499
4      5  1.9649  2.4776

### 📝 **Problema 2.2** 

**🎯 Questão:** Com base nas informações obtidas como você avaliaria a integrabilidade dos dados? Quais métricas você utilizou para chegar nesta conclusão?

*(responda aqui)*

A partir das informações exibidas ao usar `.info()`, podemos verificar que temos algumas entradas nulas nas colunas `x` e `y`. Esse fator indica que a integridade dos dados está parcialmente comprometida no quesito completude, exigindo uma etapa prévia de tratamento (como imputação de valores ou remoção de linhas nulas) antes de prosseguir com análises ou modelagens mais avançadas.

### 📝 **Problema 2.3**

**🎯 Objetivo:** Com base no exercício anterior, interpole os dados para fazer o tratamento dos dados e verifique novamente.

In [25]:
# TODO: trate os dados faltantes
df = df.dropna()

# TODO: Visualize informações da tabela
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 97 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tempo   97 non-null     int64
 1   x       97 non-null     float64
 2   y       97 non-null     float64
dtypes: float64(2), int64(1)
memory usage: 3.0 KB

### 📝 **Problema 2.4**

**🎯 Objetivo:** Crie uma visualização bidimenional utilizando as colunas x e y para visualizar o trajeto do `Albert`.

**Nota:** Utiliza a biblioteca `altair` e seus métodos para criar a visualização.

In [32]:
# TODO: faça uma visualização simples da trajetória do albert ao longo do tempo
alt.Chart(df).mark_line().encode(
    x='x:Q',
    y='y:Q',
).properties(
    title='Trajetória do Albert ao longo do tempo',
    width=500,
    height=300
)

alt.Chart(...)

### 📝 **Problema 2.5**

**🎯 Objetivo:** Crie uma coluna na estrutura de dados que mostra a distância percorrida entre as posições.

In [34]:
# TODO: crie a coluna que motra a distância percorrida entre cada passo
df['distancia'] = np.sqrt((df['x'].diff() ** 2) + (df['y'].diff() ** 2))
df['distancia'] = df['distancia'].fillna(0)  # Preencher o primeiro valor com 0'

df.head()

   tempo       x       y  distancia
0      1  0.4745  0.5973   0.000000
1      2  0.7793  1.3695   0.830178
2      3  1.2972  1.9240   0.758743
3      4  1.8285  2.2499   0.623290
4      5  1.9649  2.4776   0.265428

### 📝 **Problema 2.6**

**🎯 Objetivo:** Crie uma visualização para mostrar a distância percorrida entre as posições ao longo do tempo.

In [37]:
# TODO: faça uma visualização simples da trajetória do albert ao longo do tempo
alt.Chart(df).mark_line().encode(
    x='tempo:Q',
    y='distancia:Q',
).properties(
    title='Trajetória do Albert ao longo do tempo',
    width=500,
    height=300
)

alt.Chart(...)